/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardBudgetsBudgetIdRouteImport } from './routes/dashboard/budgets/$budgetId'
import { Route as DashboardBudgetsBudgetIdIndexRouteImport } from './routes/dashboard/budgets/$budgetId/index'
import { Route as DashboardBudgetsBudgetIdTagsRouteImport } from './routes/dashboard/budgets/$budgetId/tags'
import { Route as DashboardBudgetsBudgetIdSinksRouteImport } from './routes/dashboard/budgets/$budgetId/sinks'
import { Route as DashboardBudgetsBudgetIdSettingsRouteImport } from './routes/dashboard/budgets/$budgetId/settings'
import { Route as DashboardBudgetsBudgetIdRulesRouteImport } from './routes/dashboard/budgets/$budgetId/rules'
import { Route as DashboardBudgetsBudgetIdLedgerRouteImport } from './routes/dashboard/budgets/$budgetId/ledger'
import { Route as DashboardBudgetsBudgetIdImportRouteImport } from './routes/dashboard/budgets/$budgetId/import'
import { Route as DashboardBudgetsBudgetIdAccountsRouteImport } from './routes/dashboard/budgets/$budgetId/accounts'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBudgetsBudgetIdRoute =
  DashboardBudgetsBudgetIdRouteImport.update({
    id: '/budgets/$budgetId',
    path: '/budgets/$budgetId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBudgetsBudgetIdIndexRoute =
  DashboardBudgetsBudgetIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardBudgetsBudgetIdRoute,
  } as any)
const DashboardBudgetsBudgetIdTagsRoute =
  DashboardBudgetsBudgetIdTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => DashboardBudgetsBudgetIdRoute,
  } as any)
const DashboardBudgetsBudgetIdSinksRoute =
  DashboardBudgetsBudgetIdSinksRouteImport.update({
    id: '/sinks',
    path: '/sinks',
    getParentRoute: () => DashboardBudgetsBudgetIdRoute,
  } as any)
const DashboardBudgetsBudgetIdSettingsRoute =
  DashboardBudgetsBudgetIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardBudgetsBudgetIdRoute,
  } as any)
const DashboardBudgetsBudgetIdRulesRoute =
  DashboardBudgetsBudgetIdRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => DashboardBudgetsBudgetIdRoute,
  } as any)
const DashboardBudgetsBudgetIdLedgerRoute =
  DashboardBudgetsBudgetIdLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => DashboardBudgetsBudgetIdRoute,
  } as any)
const DashboardBudgetsBudgetIdImportRoute =
  DashboardBudgetsBudgetIdImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => DashboardBudgetsBudgetIdRoute,
  } as any)
const DashboardBudgetsBudgetIdAccountsRoute =
  DashboardBudgetsBudgetIdAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => DashboardBudgetsBudgetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/budgets/$budgetId': typeof DashboardBudgetsBudgetIdRouteWithChildren
  '/dashboard/budgets/$budgetId/accounts': typeof DashboardBudgetsBudgetIdAccountsRoute
  '/dashboard/budgets/$budgetId/import': typeof DashboardBudgetsBudgetIdImportRoute
  '/dashboard/budgets/$budgetId/ledger': typeof DashboardBudgetsBudgetIdLedgerRoute
  '/dashboard/budgets/$budgetId/rules': typeof DashboardBudgetsBudgetIdRulesRoute
  '/dashboard/budgets/$budgetId/settings': typeof DashboardBudgetsBudgetIdSettingsRoute
  '/dashboard/budgets/$budgetId/sinks': typeof DashboardBudgetsBudgetIdSinksRoute
  '/dashboard/budgets/$budgetId/tags': typeof DashboardBudgetsBudgetIdTagsRoute
  '/dashboard/budgets/$budgetId/': typeof DashboardBudgetsBudgetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/budgets/$budgetId/accounts': typeof DashboardBudgetsBudgetIdAccountsRoute
  '/dashboard/budgets/$budgetId/import': typeof DashboardBudgetsBudgetIdImportRoute
  '/dashboard/budgets/$budgetId/ledger': typeof DashboardBudgetsBudgetIdLedgerRoute
  '/dashboard/budgets/$budgetId/rules': typeof DashboardBudgetsBudgetIdRulesRoute
  '/dashboard/budgets/$budgetId/settings': typeof DashboardBudgetsBudgetIdSettingsRoute
  '/dashboard/budgets/$budgetId/sinks': typeof DashboardBudgetsBudgetIdSinksRoute
  '/dashboard/budgets/$budgetId/tags': typeof DashboardBudgetsBudgetIdTagsRoute
  '/dashboard/budgets/$budgetId': typeof DashboardBudgetsBudgetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/budgets/$budgetId': typeof DashboardBudgetsBudgetIdRouteWithChildren
  '/dashboard/budgets/$budgetId/accounts': typeof DashboardBudgetsBudgetIdAccountsRoute
  '/dashboard/budgets/$budgetId/import': typeof DashboardBudgetsBudgetIdImportRoute
  '/dashboard/budgets/$budgetId/ledger': typeof DashboardBudgetsBudgetIdLedgerRoute
  '/dashboard/budgets/$budgetId/rules': typeof DashboardBudgetsBudgetIdRulesRoute
  '/dashboard/budgets/$budgetId/settings': typeof DashboardBudgetsBudgetIdSettingsRoute
  '/dashboard/budgets/$budgetId/sinks': typeof DashboardBudgetsBudgetIdSinksRoute
  '/dashboard/budgets/$budgetId/tags': typeof DashboardBudgetsBudgetIdTagsRoute
  '/dashboard/budgets/$budgetId/': typeof DashboardBudgetsBudgetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/'
    | '/dashboard/budgets/$budgetId'
    | '/dashboard/budgets/$budgetId/accounts'
    | '/dashboard/budgets/$budgetId/import'
    | '/dashboard/budgets/$budgetId/ledger'
    | '/dashboard/budgets/$budgetId/rules'
    | '/dashboard/budgets/$budgetId/settings'
    | '/dashboard/budgets/$budgetId/sinks'
    | '/dashboard/budgets/$budgetId/tags'
    | '/dashboard/budgets/$budgetId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/dashboard'
    | '/dashboard/budgets/$budgetId/accounts'
    | '/dashboard/budgets/$budgetId/import'
    | '/dashboard/budgets/$budgetId/ledger'
    | '/dashboard/budgets/$budgetId/rules'
    | '/dashboard/budgets/$budgetId/settings'
    | '/dashboard/budgets/$budgetId/sinks'
    | '/dashboard/budgets/$budgetId/tags'
    | '/dashboard/budgets/$budgetId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/'
    | '/dashboard/budgets/$budgetId'
    | '/dashboard/budgets/$budgetId/accounts'
    | '/dashboard/budgets/$budgetId/import'
    | '/dashboard/budgets/$budgetId/ledger'
    | '/dashboard/budgets/$budgetId/rules'
    | '/dashboard/budgets/$budgetId/settings'
    | '/dashboard/budgets/$budgetId/sinks'
    | '/dashboard/budgets/$budgetId/tags'
    | '/dashboard/budgets/$budgetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/budgets/$budgetId': {
      id: '/dashboard/budgets/$budgetId'
      path: '/budgets/$budgetId'
      fullPath: '/dashboard/budgets/$budgetId'
      preLoaderRoute: typeof DashboardBudgetsBudgetIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/budgets/$budgetId/': {
      id: '/dashboard/budgets/$budgetId/'
      path: '/'
      fullPath: '/dashboard/budgets/$budgetId/'
      preLoaderRoute: typeof DashboardBudgetsBudgetIdIndexRouteImport
      parentRoute: typeof DashboardBudgetsBudgetIdRoute
    }
    '/dashboard/budgets/$budgetId/tags': {
      id: '/dashboard/budgets/$budgetId/tags'
      path: '/tags'
      fullPath: '/dashboard/budgets/$budgetId/tags'
      preLoaderRoute: typeof DashboardBudgetsBudgetIdTagsRouteImport
      parentRoute: typeof DashboardBudgetsBudgetIdRoute
    }
    '/dashboard/budgets/$budgetId/sinks': {
      id: '/dashboard/budgets/$budgetId/sinks'
      path: '/sinks'
      fullPath: '/dashboard/budgets/$budgetId/sinks'
      preLoaderRoute: typeof DashboardBudgetsBudgetIdSinksRouteImport
      parentRoute: typeof DashboardBudgetsBudgetIdRoute
    }
    '/dashboard/budgets/$budgetId/settings': {
      id: '/dashboard/budgets/$budgetId/settings'
      path: '/settings'
      fullPath: '/dashboard/budgets/$budgetId/settings'
      preLoaderRoute: typeof DashboardBudgetsBudgetIdSettingsRouteImport
      parentRoute: typeof DashboardBudgetsBudgetIdRoute
    }
    '/dashboard/budgets/$budgetId/rules': {
      id: '/dashboard/budgets/$budgetId/rules'
      path: '/rules'
      fullPath: '/dashboard/budgets/$budgetId/rules'
      preLoaderRoute: typeof DashboardBudgetsBudgetIdRulesRouteImport
      parentRoute: typeof DashboardBudgetsBudgetIdRoute
    }
    '/dashboard/budgets/$budgetId/ledger': {
      id: '/dashboard/budgets/$budgetId/ledger'
      path: '/ledger'
      fullPath: '/dashboard/budgets/$budgetId/ledger'
      preLoaderRoute: typeof DashboardBudgetsBudgetIdLedgerRouteImport
      parentRoute: typeof DashboardBudgetsBudgetIdRoute
    }
    '/dashboard/budgets/$budgetId/import': {
      id: '/dashboard/budgets/$budgetId/import'
      path: '/import'
      fullPath: '/dashboard/budgets/$budgetId/import'
      preLoaderRoute: typeof DashboardBudgetsBudgetIdImportRouteImport
      parentRoute: typeof DashboardBudgetsBudgetIdRoute
    }
    '/dashboard/budgets/$budgetId/accounts': {
      id: '/dashboard/budgets/$budgetId/accounts'
      path: '/accounts'
      fullPath: '/dashboard/budgets/$budgetId/accounts'
      preLoaderRoute: typeof DashboardBudgetsBudgetIdAccountsRouteImport
      parentRoute: typeof DashboardBudgetsBudgetIdRoute
    }
  }
}

interface DashboardBudgetsBudgetIdRouteChildren {
  DashboardBudgetsBudgetIdAccountsRoute: typeof DashboardBudgetsBudgetIdAccountsRoute
  DashboardBudgetsBudgetIdImportRoute: typeof DashboardBudgetsBudgetIdImportRoute
  DashboardBudgetsBudgetIdLedgerRoute: typeof DashboardBudgetsBudgetIdLedgerRoute
  DashboardBudgetsBudgetIdRulesRoute: typeof DashboardBudgetsBudgetIdRulesRoute
  DashboardBudgetsBudgetIdSettingsRoute: typeof DashboardBudgetsBudgetIdSettingsRoute
  DashboardBudgetsBudgetIdSinksRoute: typeof DashboardBudgetsBudgetIdSinksRoute
  DashboardBudgetsBudgetIdTagsRoute: typeof DashboardBudgetsBudgetIdTagsRoute
  DashboardBudgetsBudgetIdIndexRoute: typeof DashboardBudgetsBudgetIdIndexRoute
}

const DashboardBudgetsBudgetIdRouteChildren: DashboardBudgetsBudgetIdRouteChildren =
  {
    DashboardBudgetsBudgetIdAccountsRoute:
      DashboardBudgetsBudgetIdAccountsRoute,
    DashboardBudgetsBudgetIdImportRoute: DashboardBudgetsBudgetIdImportRoute,
    DashboardBudgetsBudgetIdLedgerRoute: DashboardBudgetsBudgetIdLedgerRoute,
    DashboardBudgetsBudgetIdRulesRoute: DashboardBudgetsBudgetIdRulesRoute,
    DashboardBudgetsBudgetIdSettingsRoute:
      DashboardBudgetsBudgetIdSettingsRoute,
    DashboardBudgetsBudgetIdSinksRoute: DashboardBudgetsBudgetIdSinksRoute,
    DashboardBudgetsBudgetIdTagsRoute: DashboardBudgetsBudgetIdTagsRoute,
    DashboardBudgetsBudgetIdIndexRoute: DashboardBudgetsBudgetIdIndexRoute,
  }

const DashboardBudgetsBudgetIdRouteWithChildren =
  DashboardBudgetsBudgetIdRoute._addFileChildren(
    DashboardBudgetsBudgetIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBudgetsBudgetIdRoute: typeof DashboardBudgetsBudgetIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBudgetsBudgetIdRoute: DashboardBudgetsBudgetIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
