export const BUDGET_CORE_VERSION = "0.0.0";

export {
  CURRENT_EVENT_VERSION,
  CURRENT_STATE_VERSION,
  CurrencyCodeSchema,
  DEFAULT_ENTITY_COLOR,
  EntityIdSchema,
  HexColorSchema,
  IsoDateSchema,
  IsoDateTimeSchema,
  MembershipRoleSchema,
  MoneyAmountSchema,
} from "./common.ts";
export type {
  CurrencyCode,
  EntityId,
  HexColor,
  IsoDate,
  IsoDateTime,
  MembershipRole,
  MoneyAmount,
} from "./common.ts";

export {
  AccountSchema,
  CategorySchema,
  ColumnMappingSchema,
  EventTagSchema,
  GenesisEpochSchema,
  LedgerTransactionSchema,
  LifestyleTagSchema,
  NumberFormatSchema,
  ParserTemplateSchema,
  RawTransactionSchema,
  RuleSchema,
  SinkSchema,
  SplitGroupSchema,
  VirtualSliceSchema,
} from "./budget/entities.ts";
export type {
  Account,
  Category,
  ColumnMapping,
  EventTag,
  GenesisEpoch,
  LedgerTransaction,
  LifestyleTag,
  NumberFormat,
  ParserTemplate,
  RawTransaction,
  Rule,
  Sink,
  SplitGroup,
  VirtualSlice,
} from "./budget/entities.ts";

export { BudgetMetadataSchema } from "./budget/metadata.ts";
export type { BudgetMetadata } from "./budget/metadata.ts";

export {
  BudgetStateSchema,
  BudgetStateV1Schema,
  INITIAL_BUDGET_STATE,
} from "./budget/state.ts";
export type { BudgetState, BudgetStateV1 } from "./budget/state.ts";

export {
  AccountAddedPayloadSchema,
  AccountBalanceAdjustedPayloadSchema,
  CategoryCreatedPayloadSchema,
  CategoryUpdatedPayloadSchema,
  EventTagArchivedPayloadSchema,
  EventTagCreatedPayloadSchema,
  EventTagUpdatedPayloadSchema,
  GenesisEpochSetPayloadSchema,
  ImportedRawTransactionSchema,
  IncomeSlicedPayloadSchema,
  InternalTransferRecordedPayloadSchema,
  LedgerTransactionCreatedPayloadSchema,
  LedgerTransactionUpdatedPayloadSchema,
  LifestyleTagCreatedPayloadSchema,
  LifestyleTagUpdatedPayloadSchema,
  ParserTemplateConfiguredPayloadSchema,
  RuleCreatedPayloadSchema,
  RuleUpdatedPayloadSchema,
  SinkCapUpdatedPayloadSchema,
  SinkCreatedPayloadSchema,
  SinkFundedPayloadSchema,
  SinkWithdrawnPayloadSchema,
  SplitInitiatedPayloadSchema,
  SplitLinkedPayloadSchema,
  TransactionsImportedPayloadSchema,
  VirtualSliceDefinedSchema,
} from "./events/payloads.ts";
export type {
  AccountAddedPayload,
  AccountBalanceAdjustedPayload,
  CategoryCreatedPayload,
  CategoryUpdatedPayload,
  EventTagArchivedPayload,
  EventTagCreatedPayload,
  EventTagUpdatedPayload,
  GenesisEpochSetPayload,
  ImportedRawTransaction,
  IncomeSlicedPayload,
  InternalTransferRecordedPayload,
  LedgerTransactionCreatedPayload,
  LedgerTransactionUpdatedPayload,
  LifestyleTagCreatedPayload,
  LifestyleTagUpdatedPayload,
  ParserTemplateConfiguredPayload,
  RuleCreatedPayload,
  RuleUpdatedPayload,
  SinkCapUpdatedPayload,
  SinkCreatedPayload,
  SinkFundedPayload,
  SinkWithdrawnPayload,
  SplitInitiatedPayload,
  SplitLinkedPayload,
  TransactionsImportedPayload,
} from "./events/payloads.ts";

export {
  AccountAddedEventSchema,
  AccountBalanceAdjustedEventSchema,
  AppendEventInputSchema,
  CategoryCreatedEventSchema,
  CategoryUpdatedEventSchema,
  DomainEventSchema,
  EVENT_TYPES,
  EventTagArchivedEventSchema,
  EventTagCreatedEventSchema,
  EventTagUpdatedEventSchema,
  EventTypeSchema,
  GenesisEpochSetEventSchema,
  IncomeSlicedEventSchema,
  InternalTransferRecordedEventSchema,
  LedgerTransactionCreatedEventSchema,
  LedgerTransactionUpdatedEventSchema,
  LifestyleTagCreatedEventSchema,
  LifestyleTagUpdatedEventSchema,
  ParserTemplateConfiguredEventSchema,
  RuleCreatedEventSchema,
  RuleUpdatedEventSchema,
  SinkCapUpdatedEventSchema,
  SinkCreatedEventSchema,
  SinkFundedEventSchema,
  SinkWithdrawnEventSchema,
  SplitInitiatedEventSchema,
  SplitLinkedEventSchema,
  StoredEventSchema,
  TransactionsImportedEventSchema,
} from "./events/domain-event.ts";
export type {
  AppendEventInput,
  DomainEvent,
  EventType,
  StoredEvent,
} from "./events/domain-event.ts";

export {
  reduceBudgetState,
  replayBudgetEvents,
  applyEventToDraft,
} from "./reducer.ts";
